### ISSUE TITLE
Support `hx-swap` modifiers in a type-safe way

### ISSUE THREAD

**Issue by angelofallars** [angelofallars/htmx-go#1]
After some research, it turns out that HTMX supports modifier attributes in `hx-swap`. E.g. `swap:1s`, `settle:1s` and `scroll:bottom`. https://htmx.org/attributes/hx-swap/

There's a lot of possible modifier attributes, but most of them can be represented by a finite amount of values. I'd like to see an implementation that is **type-safe** as much as possible.

Example possible implementations:

```go
htmx.NewResponse().
  Reswap(htmx.SwapWithAttr(htmx.SwapOuterHTML, htmx.ModFocusScroll(true))
// [Output header]
// HX-Reswap: outerHTML focus-scroll:true

htmx.NewResponse().
  Reswap(htmx.SwapWithAttr(htmx.SwapBeforeEnd, htmx.ModScrollBottom())
// [Output header]
// HX-Reswap: beforeEnd scroll:bottom

htmx.NewResponse().
  Reswap(htmx.SwapWithAttr(htmx.SwapInnerHTML, htmx.ModShowTop("#another-div"))
// [Output header]
// HX-Reswap: innerHTML show:#another-div:top
```

Edit: This possible implementation looks good too, implementing methods on the `htmx.swapStrategy` type (which is just derived from `string`) that return a new `swapStrategy` value:

```go
htmx.NewResponse().
  Reswap(htmx.SwapOuterHTML.FocusScroll(true))
// [Output header]
// HX-Reswap: outerHTML focus-scroll:true

htmx.NewResponse().
  Reswap(htmx.SwapBeforeEnd.ScrollBottom())
// [Output header]
// HX-Reswap: beforeEnd scroll:bottom

htmx.NewResponse().
  Reswap(htmx.SwapInnerHTML.ShowTop("#another-div"))
// [Output header]
// HX-Reswap: innerHTML show:#another-div:top
```

**Comment by rafiramadhana** [comment]
@angelofallars is there anything that is expected to change beside the headers? (`htmx.Response.Headers()`)

**Comment by rafiramadhana** [comment]
btw is it possible for the `hx-swap` to have more than one modifiers?

something like

```
// HX-Reswap: outerHTML focus-scroll:true scroll:bottom
```

**Comment by angelofallars** [comment]
> btw is it possible for the `hx-swap` to have more than one modifiers?
> 
> something like
> 
> ```
> // HX-Reswap: outerHTML focus-scroll:true scroll:bottom
> ```

Yes, with method chaining:
```go
htmx.SwapOuterHTML.FocusScroll(true).ScrollBottom()
```

**Comment by rafiramadhana** [comment]
> Yes, with method chaining:

i see, i think the requirement is clear enough now

i will create a draft PR for #1

**Comment by rafiramadhana** [comment]
@angelofallars would you mind to check the draft PR? https://github.com/angelofallars/htmx-go/pull/3

it covers the proposal on how to set modifiers

but it has not covered all of the mentioned modifiers in https://htmx.org/attributes/hx-swap

the remaining modifiers will be covered once we agreed with the proposal

thanks!
